In [47]:
import tensorflow as tf
import pandas as pd
import numpy as np
from tensorflow.keras.models import load_model
import pickle

In [48]:
### Load the trained model, scaler pickle,onehot
model=load_model('model.h5')

## load the encoder and scaler
with open('columnTransformer.pkl','rb') as file:
    ct=pickle.load(file)

with open('scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)

In [30]:
# Example input data
# input_data = {
#     'CreditScore': 600,
#     'Geography': 'France',
#     'Gender': 'Male',
#     'Age': 40,
#     'Tenure': 3,
#     'Balance': 60000,
#     'NumOfProducts': 2,
#     'HasCrCard': 1,
#     'IsActiveMember': 1,
#     'EstimatedSalary': 50000
# }

In [49]:
input_data = [
    [600, 'France', 'Male', 40, 3, 60000, 2, 1, 1, 50000]
]


In [50]:
x =np.array(ct.transform(input_data))
x

array([[1.0, 0.0, 0.0, 0.0, 1.0, 600, 40, 3, 60000, 2, 1, 1, 50000]],
      dtype=object)

In [51]:
x[:, 5:]=scaler.transform(x[:, 5:])
x

array([[1.0, 0.0, 0.0, 0.0, 1.0, -0.5359851613060699,
        0.10479359289024653, -0.695393486155178, -0.2578111881087735,
        0.8084361535388407, 0.6492026709982338, 0.9748169889123993,
        -0.8768322080152661]], dtype=object)

In [54]:
input_scaled = x.astype('float32')

In [55]:
prediction=model.predict(input_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step


array([[0.03802957]], dtype=float32)

In [56]:
prediction_proba = prediction[0][0]

In [58]:
float(prediction_proba)

0.03802957013249397

In [59]:
if prediction_proba > 0.5:
    print('The customer is likely to churn.')
else:
    print('The customer is not likely to churn.')

The customer is not likely to churn.


### finished